site_name: ARGOS Toolkit
site_description: Aerospace Research for GNC Operational Scenarios toolkit
site_url: https://rodandres.github.io/ARGOS-Toolkit/

theme:
  name: material

  palette:
    - scheme: default
      primary: cyan
      accent: green

  logo: assets/logo_placeholder.svg

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: numpy
nav:
  - Home: index.md
  - API Reference:
      - Overview: api/index.md
      - Actuators: api/actuators.md
      - Cislunar Astrodynamics: api/cislunar_astrodynamics.md
      - Controllers: api/controllers.md
      - Core: api/core.md
      - Enviroments: api/enviroments.md
      - Faults: api/faults.md
      - General: api/general.md
      - Guidance: api/guidance.md
      - Navigation: api/navigation.md
      - Propagators: api/propagators.md
      - Sensors: api/sensors.md
      - Solvers: api/solvers.md
