import os
import numpy as np
import matplotlib.pyplot as plt


# ==============================================================================
# CONFIGURATION
# ==============================================================================

chaser_name = "Chaser"
target_name = "Target"

HISTORY_DIRECTORY = "simulation_history"

TIME_FACTOR_SEC = 27.321661 / (2.0 * np.pi) * 24 * 3600     # time unit unidad -> sideral lunar month (days)

SIM_MAX_TIME = 0.75952417*2 * TIME_FACTOR_SEC #60*13

ORBIT_MAX_TIME = SIM_MAX_TIME
RELATIVE_MAX_TIME = 60 * 12


# ==============================================================================
# LOAD HISTORY FROM CSV
# ==============================================================================

def load_spacecraft_history(
    spacecraft_name,
    directory,
):
    """
    Loads the time and true position history of a spacecraft
    from the CSV files generated by save_simulation_history_csv().
    """

    spacecraft_directory = os.path.join(
        directory,
        spacecraft_name,
    )

    t_path = os.path.join(
        spacecraft_directory,
        "t.csv",
    )

    position_path = os.path.join(
        spacecraft_directory,
        "true_state_position.csv",
    )

    if not os.path.isfile(t_path):
        raise FileNotFoundError(
            f"Time history not found:\n{t_path}"
        )

    if not os.path.isfile(position_path):
        raise FileNotFoundError(
            f"Position history not found:\n{position_path}"
        )

    # --------------------------------------------------------------------------
    # Time
    # --------------------------------------------------------------------------

    t = np.loadtxt(
        t_path,
        delimiter=",",
        skiprows=1,
    )

    # --------------------------------------------------------------------------
    # Position
    # --------------------------------------------------------------------------

    position = np.loadtxt(
        position_path,
        delimiter=",",
    )

    position = np.atleast_2d(position)

    if position.shape[1] != 3:
        raise ValueError(
            f"{spacecraft_name}: position must have shape (N, 3), "
            f"but got {position.shape}."
        )

    return t, position


# ==============================================================================
# LOAD CHASER AND TARGET
# ==============================================================================

chaser_t, chaser_position = load_spacecraft_history(
    chaser_name,
    HISTORY_DIRECTORY,
)

target_t, target_position = load_spacecraft_history(
    target_name,
    HISTORY_DIRECTORY,
)


# ==============================================================================
# VALIDATE DATA
# ==============================================================================

if len(chaser_t) != len(chaser_position):

    raise ValueError(
        f"{chaser_name}: time and position have different lengths: "
        f"{len(chaser_t)} vs {len(chaser_position)}"
    )


if len(target_t) != len(target_position):

    raise ValueError(
        f"{target_name}: time and position have different lengths: "
        f"{len(target_t)} vs {len(target_position)}"
    )


# ==============================================================================
# SORT BY TIME
# ==============================================================================

chaser_indices = np.argsort(chaser_t)

chaser_t = chaser_t[chaser_indices]
chaser_position = chaser_position[chaser_indices]


target_indices = np.argsort(target_t)

target_t = target_t[target_indices]
target_position = target_position[target_indices]


# ==============================================================================
# COMMON TIME FOR COMPLETE ORBIT
# ==============================================================================

orbit_t_min = max(
    chaser_t[0],
    target_t[0],
)

orbit_t_max = min(
    chaser_t[-1],
    target_t[-1],
    ORBIT_MAX_TIME,
)

if orbit_t_max <= orbit_t_min:

    raise ValueError(
        "No common time interval exists for the complete orbit."
    )


chaser_orbit_t = chaser_t[
    (chaser_t >= orbit_t_min)
    &
    (chaser_t <= orbit_t_max)
]

target_orbit_t = target_t[
    (target_t >= orbit_t_min)
    &
    (target_t <= orbit_t_max)
]


orbit_t = np.unique(
    np.concatenate(
        [
            chaser_orbit_t,
            target_orbit_t,
        ]
    )
)


# ==============================================================================
# INTERPOLATE COMPLETE ORBIT
# ==============================================================================

chaser_orbit_position = np.column_stack(
    [
        np.interp(
            orbit_t,
            chaser_t,
            chaser_position[:, i],
        )
        for i in range(3)
    ]
)


target_orbit_position = np.column_stack(
    [
        np.interp(
            orbit_t,
            target_t,
            target_position[:, i],
        )
        for i in range(3)
    ]
)


# ==============================================================================
# COMMON TIME FOR RELATIVE MOTION
# ==============================================================================

relative_t_min = max(
    chaser_t[0],
    target_t[0],
)

relative_t_max = min(
    chaser_t[-1],
    target_t[-1],
    RELATIVE_MAX_TIME,
)

if relative_t_max <= relative_t_min:

    raise ValueError(
        "No common time interval exists for the relative motion."
    )


chaser_relative_t = chaser_t[
    (chaser_t >= relative_t_min)
    &
    (chaser_t <= relative_t_max)
]

target_relative_t = target_t[
    (target_t >= relative_t_min)
    &
    (target_t <= relative_t_max)
]


relative_t = np.unique(
    np.concatenate(
        [
            chaser_relative_t,
            target_relative_t,
        ]
    )
)


# ==============================================================================
# INTERPOLATE RELATIVE MOTION
# ==============================================================================

chaser_relative_position = np.column_stack(
    [
        np.interp(
            relative_t,
            chaser_t,
            chaser_position[:, i],
        )
        for i in range(3)
    ]
)


target_relative_position = np.column_stack(
    [
        np.interp(
            relative_t,
            target_t,
            target_position[:, i],
        )
        for i in range(3)
    ]
)


# ==============================================================================
# RELATIVE POSITION
#
# r_C/T = r_C - r_T
# ==============================================================================

relative_position = (
    chaser_relative_position
    - target_relative_position
)


# ==============================================================================
# FIGURE
# ==============================================================================

fig = plt.figure(
    figsize=(18, 6),
)


# ==============================================================================
# SUBPLOT 1 — ABSOLUTE ORBIT
# ==============================================================================

ax1 = fig.add_subplot(
    1,
    3,
    1,
    projection="3d",
)


ax1.plot(
    chaser_orbit_position[:, 0],
    chaser_orbit_position[:, 1],
    chaser_orbit_position[:, 2],
    label=chaser_name,
)


ax1.plot(
    target_orbit_position[:, 0],
    target_orbit_position[:, 1],
    target_orbit_position[:, 2],
    label=target_name,
)


# Moon position in CR3BP

MU = 1.215e-2
LENGTH_FACTOR = 384400.0e3

ax1.scatter(
    (1 - MU) * LENGTH_FACTOR,
    0,
    0,
    marker="o",
    color="white",
    edgecolors="black",
    label="Moon",
)


ax1.set_title(
    f"Complete Orbit (During 1 rev) - NRHO L2",
    fontweight="bold"
)

ax1.set_xlabel("X [m]")
ax1.set_ylabel("Y [m]")
ax1.set_zlabel("Z [m]")

ax1.legend()


# ==============================================================================
# SUBPLOT 2 — RELATIVE POSITION VS TIME
# ==============================================================================

ax2 = fig.add_subplot(
    1,
    3,
    2,
)


labels = (
    r"$\Delta x$",
    r"$\Delta y$",
    r"$\Delta z$",
)


for i in range(3):

    ax2.plot(
        relative_t,
        relative_position[:, i],
        linewidth=1.3,
        label=labels[i],
    )


ax2.axhline(
    0.0,
    linestyle="--",
    linewidth=0.8,
)


ax2.set_title(
    "Relative Position",
    fontweight="bold"
)

ax2.set_xlabel(
    "Time [s]"
)

ax2.set_ylabel(
    "Relative Position [m]"
)

ax2.set_xlim(
    relative_t_min,
    relative_t_max,
)

ax2.legend(
    fontsize=8,
)


# ==============================================================================
# SUBPLOT 3 — RELATIVE TRAJECTORY
# ==============================================================================

ax3 = fig.add_subplot(
    1,
    3,
    3,
    projection="3d",
)


ax3.plot(
    relative_position[:, 0],
    relative_position[:, 1],
    relative_position[:, 2],
    linewidth=1.3,
    label=chaser_name,
)


# Target fixed at origin

ax3.scatter(
    0.0,
    0.0,
    0.0,
    marker="o",
    s=50,
    label=target_name,
)


# Initial relative position

ax3.scatter(
    relative_position[0, 0],
    relative_position[0, 1],
    relative_position[0, 2],
    marker="o",
    s=35,
    label="Chaser Relative Initial Position",
)


# Final relative position

ax3.scatter(
    relative_position[-1, 0],
    relative_position[-1, 1],
    relative_position[-1, 2],
    marker="x",
    s=50,
    label="Chaser Relative Final Position",
)


ax3.set_title(
    "Relative Trajectory",
    fontweight="bold"
)

ax3.set_xlabel(
    r"$\Delta x$ [m]"
)

ax3.set_ylabel(
    r"$\Delta y$ [m]"
)

ax3.set_zlabel(
    r"$\Delta z$ [m]"
)

ax3.legend(
    fontsize=8,
)


# Rotate camera

ax3.view_init(
    elev=25,
    azim=135,
)


# ==============================================================================
# EQUAL ASPECT RATIO FOR 3D PLOTS
# ==============================================================================

def set_equal_3d_axes(ax, data):

    x = data[:, 0]
    y = data[:, 1]
    z = data[:, 2]

    x_range = np.ptp(x)
    y_range = np.ptp(y)
    z_range = np.ptp(z)

    max_range = max(
        x_range,
        y_range,
        z_range,
    )

    if max_range == 0:
        max_range = 1.0

    x_mid = (
        x.max()
        + x.min()
    ) / 2

    y_mid = (
        y.max()
        + y.min()
    ) / 2

    z_mid = (
        z.max()
        + z.min()
    ) / 2

    ax.set_xlim(
        x_mid - max_range / 2,
        x_mid + max_range / 2,
    )

    ax.set_ylim(
        y_mid - max_range / 2,
        y_mid + max_range / 2,
    )

    ax.set_zlim(
        z_mid - max_range / 2,
        z_mid + max_range / 2,
    )


set_equal_3d_axes(
    ax1,
    np.vstack(
        [
            chaser_orbit_position,
            target_orbit_position,
        ]
    ),
)


set_equal_3d_axes(
    ax3,
    np.vstack(
        [
            relative_position,
            np.zeros((1, 3)),
        ]
    ),
)


# ==============================================================================
# FIGURE TITLE
# ==============================================================================

fig.suptitle(
    f"SIMULATION RESULTS - TRAJECTORIES",
    fontsize=14,
    fontweight="bold"
)


fig.tight_layout(
    rect=[0, 0, 1, 0.94],
)


# ==============================================================================
# SHOW
# ==============================================================================

plt.show()

# ============================================================================
# CHASER CONTROL RESULT
# ============================================================================

chaser_directory = os.path.join(
    HISTORY_DIRECTORY,
    chaser_name,
)


# ============================================================================
# LOAD CONTROL DATA
# ============================================================================

control_force = np.loadtxt(
    os.path.join(
        chaser_directory,
        "control_output_data_force.csv",
    ),
    delimiter=",",
)

applied_force = np.loadtxt(
    os.path.join(
        chaser_directory,
        "force.csv",
    ),
    delimiter=",",
)

control_torque = np.loadtxt(
    os.path.join(
        chaser_directory,
        "control_output_data_torque.csv",
    ),
    delimiter=",",
)

applied_torque = np.loadtxt(
    os.path.join(
        chaser_directory,
        "torque.csv",
    ),
    delimiter=",",
)


# ============================================================================
# ENSURE 2D ARRAYS
# ============================================================================

control_force = np.atleast_2d(
    control_force
)

applied_force = np.atleast_2d(
    applied_force
)

control_torque = np.atleast_2d(
    control_torque
)

applied_torque = np.atleast_2d(
    applied_torque
)


# ============================================================================
# VALIDATE DATA
# ============================================================================

if len(chaser_t) != len(control_force):
    raise ValueError(
        "Chaser time and commanded force have different lengths: "
        f"{len(chaser_t)} vs {len(control_force)}"
    )

if len(chaser_t) != len(applied_force):
    raise ValueError(
        "Chaser time and applied force have different lengths: "
        f"{len(chaser_t)} vs {len(applied_force)}"
    )

if len(chaser_t) != len(control_torque):
    raise ValueError(
        "Chaser time and commanded torque have different lengths: "
        f"{len(chaser_t)} vs {len(control_torque)}"
    )

if len(chaser_t) != len(applied_torque):
    raise ValueError(
        "Chaser time and applied torque have different lengths: "
        f"{len(chaser_t)} vs {len(applied_torque)}"
    )

if control_force.shape[1] != 3:
    raise ValueError(
        f"Commanded force must have shape (N, 3), "
        f"but got {control_force.shape}"
    )

if applied_force.shape[1] != 3:
    raise ValueError(
        f"Applied force must have shape (N, 3), "
        f"but got {applied_force.shape}"
    )

if control_torque.shape[1] != 3:
    raise ValueError(
        f"Commanded torque must have shape (N, 3), "
        f"but got {control_torque.shape}"
    )

if applied_torque.shape[1] != 3:
    raise ValueError(
        f"Applied torque must have shape (N, 3), "
        f"but got {applied_torque.shape}"
    )


# ============================================================================
# SORT BY TIME
# ============================================================================

control_indices = np.argsort(chaser_t)

chaser_control_t = chaser_t[control_indices]

control_force = control_force[
    control_indices
]

applied_force = applied_force[
    control_indices
]

control_torque = control_torque[
    control_indices
]

applied_torque = applied_torque[
    control_indices
]


# ============================================================================
# LIMIT TO RELATIVE_MAX_TIME
# ============================================================================

control_mask = (
    chaser_control_t <= RELATIVE_MAX_TIME
)

control_t = chaser_control_t[
    control_mask
]

control_force = control_force[
    control_mask
]

applied_force = applied_force[
    control_mask
]

control_torque = control_torque[
    control_mask
]

applied_torque = applied_torque[
    control_mask
]


if len(control_t) == 0:
    raise ValueError(
        "No Chaser control data exists within RELATIVE_MAX_TIME."
    )


# ============================================================================
# FIGURE
# ============================================================================

fig, axes = plt.subplots(
    3,
    2,
    figsize=(13, 9),
    sharex=True,
)


# ============================================================================
# FORCE / TORQUE
# ============================================================================

labels = (
    "X",
    "Y",
    "Z",
)


for i, label in enumerate(labels):

    # ------------------------------------------------------------------------
    # FORCE
    # ------------------------------------------------------------------------

    ax = axes[i, 0]

    ax.plot(
        control_t,
        control_force[:, i],
        linestyle="--",
        label="Commanded",
        zorder=2
    )

    ax.plot(
        control_t,
        applied_force[:, i],
        linestyle="-",
        label="Applied",
        zorder=1
    )

    ax.set_title(
        f"Force {label}",
        fontweight="bold"
    )

    ax.set_ylabel(
        r"$F_{" + label.lower() + r"}$ [N]"
    )

    ax.legend()


    # ------------------------------------------------------------------------
    # TORQUE
    # ------------------------------------------------------------------------

    ax = axes[i, 1]

    ax.plot(
        control_t,
        control_torque[:, i],
        linestyle="--",
        label="Commanded",
        zorder=2
    )

    ax.plot(
        control_t,
        applied_torque[:, i],
        linestyle="-",
        label="Applied",
        zorder=1
    )

    ax.set_title(
        f"Torque {label}",
        fontweight="bold"
    )

    ax.set_ylabel(
        r"$\tau_{" + label.lower() + r"}$ [N·m]"
    )

    ax.legend()


# ============================================================================
# X AXIS
# ============================================================================

axes[-1, 0].set_xlabel(
    "Time [s]"
)

axes[-1, 1].set_xlabel(
    "Time [s]"
)


# ============================================================================
# FIGURE TITLE
# ============================================================================

fig.suptitle(
    f'SIMULATION RESULT - CONTROL EFFORT CHASER',
    fontsize=14,
    fontweight="bold"
)

fig.tight_layout()


# ============================================================================
# SHOW
# ============================================================================

plt.show()