from abc import ABC, abstractmethod

import numpy as np

from py.general.data_classes_declaration import SimSharedData
from py.modules.math import quaternion_to_DCM


class PerturbationBase(ABC):
    """
    Abstract interface for external disturbance torque models.
    """

    @abstractmethod
    def compute_perturbation(
        self,
        shared_data: SimSharedData,
        inertia_matrix: np.ndarray,
    ) -> np.ndarray:
        """
        Compute the disturbance torque acting on the spacecraft.

        Parameters
        ----------
        shared_data : SimSharedData
            Shared simulation data.

        inertia_matrix : np.ndarray
            Spacecraft inertia matrix.

        Returns
        -------
        np.ndarray
            Disturbance torque expressed in the body frame.
        """
        pass


class GravityGradientPerturbation(PerturbationBase):
    """
    Gravity-gradient disturbance torque model.

    Computes the torque generated by the non-uniform gravitational field
    acting on an extended rigid body.
    """

    def __init__(
        self,
        gravitational_parameter: float,
        inertial_position: np.ndarray,
    ):
        self.gravitational_parameter = gravitational_parameter
        self.inertial_position = inertial_position

    def compute_perturbation(
        self,
        shared_data: SimSharedData,
        inertia_matrix: np.ndarray,
    ) -> np.ndarray:

        # ==========================================================
        # State retrieval
        # ==========================================================

        quaternion = shared_data.actual_q

        # ==========================================================
        # Position transformation
        # ==========================================================

        position_norm = np.linalg.norm(
            self.inertial_position
        )

        rotation_matrix = quaternion_to_DCM(
            quaternion
        )

        body_position = (
            rotation_matrix.T
            @ self.inertial_position
        )

        body_position /= np.linalg.norm(body_position)

        # ==========================================================
        # Gravity-gradient torque
        # ==========================================================

        gravity_gradient_factor = (
            3.0
            * self.gravitational_parameter
            / position_norm**3
        )

        disturbance_torque = (
            gravity_gradient_factor
            * np.cross(
                body_position,
                inertia_matrix @ body_position,
            )
        )

        return disturbance_torque


class SolarPressurePerturbation(PerturbationBase):
    """
    Solar radiation pressure disturbance torque model.
    """

    def __init__(
        self,
        solar_pressure: float,
        reflectivity_coefficient: float,
        exposed_area: float,
        center_of_pressure_offset: np.ndarray,
        surface_normal_body: np.ndarray,
        sun_direction_inertial: np.ndarray,
    ):

        self.solar_pressure = solar_pressure
        self.reflectivity_coefficient = reflectivity_coefficient

        self.exposed_area = exposed_area

        self.center_of_pressure_offset = center_of_pressure_offset

        self.surface_normal_body = surface_normal_body
        self.sun_direction_inertial = sun_direction_inertial

    def compute_perturbation(
        self,
        shared_data: SimSharedData,
        inertia_matrix: np.ndarray,
    ) -> np.ndarray:

        # ==========================================================
        # State retrieval
        # ==========================================================

        quaternion = shared_data.actual_q

        # ==========================================================
        # Sun direction transformation
        # ==========================================================

        rotation_matrix = quaternion_to_DCM(
            quaternion
        )

        sun_direction_body = (
            rotation_matrix.T
            @ self.sun_direction_inertial
        )

        sun_direction_body /= np.linalg.norm(
            sun_direction_body
        )

        # ==========================================================
        # Solar radiation pressure force
        # ==========================================================

        projected_area = (
            self.exposed_area
            * max(
                0.0,
                np.dot(
                    self.surface_normal_body,
                    sun_direction_body,
                ),
            )
        )

        solar_force = (
            self.solar_pressure
            * self.reflectivity_coefficient
            * projected_area
            * sun_direction_body
        )

        # ==========================================================
        # Disturbance torque
        # ==========================================================

        disturbance_torque = np.cross(
            self.center_of_pressure_offset,
            solar_force,
        )

        return disturbance_torque