from abc import ABC, abstractmethod

from argos.general.dataclasses import NavigationOutput, SimulationData, GuidanceOutput

class GuidanceBase(ABC):
    """
    Abstract base class for spacecraft guidance laws.

    Guidance laws use navigation information and simulation data to compute
    the desired spacecraft reference state.
    """
    def __init__(self):
        """
        Initialize the guidance law and validate its configuration.
        """
        self._check_initialization()

    @abstractmethod
    def _check_initialization(self):
        """
        Validate the guidance law initialization.

        Subclasses implement this method to verify that their configuration is
        valid.

        Raises
        ------
        Exception
            Subclasses may raise an appropriate exception when the guidance law
            configuration is invalid.
        """      

    @abstractmethod
    def compute_reference(
        self,
        navigationdata: NavigationOutput,
        simulation_data: SimulationData,
    ) -> GuidanceOutput:
        """
        Compute the desired spacecraft guidance reference.

        Parameters
        ----------
        navigationdata : NavigationOutput
            Current navigation output for the spacecraft.
        simulation_data : SimulationData
            Current simulation data.

        Returns
        -------
        GuidanceOutput
            Desired spacecraft state generated by the guidance law.

        Raises
        ------
        NotImplementedError
            Subclasses must implement this method.
        """