from abc import ABC, abstractmethod

import numpy as np
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from argos.general.dataclasses import ActuatorOutput

class ActuatorBase(ABC):
    """
    Abstract base class for spacecraft actuators.

    Actuators receive commands from the control and actuation system,
    update their internal state, and provide the resulting force and
    torque output applied to the spacecraft.

    Parameters
    ----------
    name : str
        Actuator identifier.

    Attributes
    ----------
    available : bool
        Indicates whether the actuator is available for use.
    used : bool
        Indicates whether the actuator has been used at least once.
    controllable : bool
        Indicates whether the actuator can currently be controlled.
    name : str
        Actuator identifier.
    override_torque : bool
        Indicates whether the actuator uses an externally specified torque
        instead of the torque computed from its force and position.
    """

    def __init__(self, name: str):        
        self.available = True  # Flag to indicate if the actuator is available for use
        self.used = False  # Flag to indicate if the actuator has been used at least once
        self.controllable = True  # Flag to indicate if the actuator can be controlled
        self.name = name

        self.override_torque = False

    @abstractmethod 
    def set_command(self, command):  # Saves the value of force or torque command for later application.
        """
        Set the command received by the actuator.

        Parameters
        ----------
        command
            Actuator command. The expected type and meaning depend on the
            concrete actuator implementation.
        """
        pass

    @abstractmethod
    def update(self, local_time: float) -> np.ndarray:
        """
        Update the actuator state for the current local simulation time.

        Parameters
        ----------
        local_time : float
            Current actuator-local simulation time [s].

        Returns
        -------
        ndarray
            Actuator output or updated actuator state, depending on the
            concrete implementation.
        """
        pass

    @abstractmethod
    def get_output(self) -> 'ActuatorOutput':
        """
        Return the current actuator output.

        Returns
        -------
        ActuatorOutput
            Current force and torque generated by the actuator.
        """
        pass

    @abstractmethod
    def print_information(self):
        """
        Print actuator information to the console.
        """
        pass

    def is_available(self) -> bool: #NOTE: This should be remove
        """
        Check if the actuator is available for use.
        """
        return self.available

    def is_controllable(self) -> bool: #NOTE: This should be remove
        """
        Check if the actuator can be controlled.
        """
        return self.controllable

    def has_been_used(self) -> bool: #NOTE: This should be remove
        """
        Check if the actuator has been used at least once.
        """
        return self.used