from abc import ABC, abstractmethod

import numpy as np
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from py.general.dataclasses import ActuatorOutput

class ActuatorBase(ABC):
    """
    Abstract interface for all spacecraft actuators.

    Every actuator must implement a command update stage and a command
    execution stage.    
    """

    def __init__(self):        
        self.is_available = True  # Flag to indicate if the actuator is available for use
        self.has_been_used = False  # Flag to indicate if the actuator has been used at least once
        self.is_controlable = True  # Flag to indicate if the actuator can be controlled

        self.override_torque = False

    @abstractmethod 
    def set_command(self, command):  # Saves the value of force or torque command for later application.
        """
        Store or process the commanded actuator input.
        """
        pass

    @abstractmethod
    def update(self, local_time: float) -> np.ndarray:
        """
        Update the actuator state based on the current time.
        """
        pass

    @abstractmethod
    def get_output(self) -> 'ActuatorOutput':
        """
        Return the current output of the actuator.
        """
        pass


class RCSThruster_old(ActuatorBase):
    """
    Single RCS thruster model.

    The thruster produces torque about one body axis only. Command allocation
    is performed externally; this class simply converts the requested torque
    into either a PWM duty cycle or a bang-bang firing command.
    """

    def __init__(
        self,
        controlled_axis: int,
        thrust_direction: int,
        maximum_torque: float,
        command_mode: str = "PWM",
        modulation_window: float = 0.5,
        minimum_on_time: float = 0.01,
        activation_threshold: float = 0.0,
    ):
        """
        Parameters
        ----------
        controlled_axis : int
            Body axis controlled by the thruster.

                0 -> X
                1 -> Y
                2 -> Z

        thrust_direction : int
            Torque direction generated by the thruster.

                +1
                -1

        maximum_torque : float
            Maximum torque delivered by the thruster [N·m].

        command_mode : str, optional
            Thruster command strategy.

                - "PWM"
                - "bangbang"

        modulation_window : float, optional
            PWM modulation window [s].

        minimum_on_time : float, optional
            Minimum valve opening time [s].

        activation_threshold : float, optional
            Bang-bang activation threshold [N·m].
        """

        self.controlled_axis = controlled_axis
        self.thrust_direction = np.sign(thrust_direction)

        self.maximum_torque = maximum_torque

        self.command_mode = command_mode

        self.modulation_window = modulation_window
        self.minimum_on_time = minimum_on_time

        self.activation_threshold = activation_threshold

        # ==========================================================
        # Internal actuator state
        # ==========================================================

        self.on_time = 0.0
        self.is_firing = False

    # ==========================================================
    # Public interface
    # ==========================================================

    def set_command(self, desired_torque: np.ndarray):
        """
        Compute the internal actuator command from the requested body torque.
        """

        commanded_axis_torque = desired_torque[self.controlled_axis]

        # Project the requested torque onto the actuator direction.
        projected_torque = (
            commanded_axis_torque * self.thrust_direction
        )

        # A negative projection means that this thruster cannot contribute.
        if projected_torque <= 0.0:

            self.on_time = 0.0
            self.is_firing = False
            return

        if self.command_mode == "PWM":

            self._compute_pwm_command(projected_torque)

        elif self.command_mode == "bangbang":

            self._compute_bangbang_command(projected_torque)

        else:
            raise ValueError(
                f"Unsupported command mode: {self.command_mode}"
            )

    def apply_command(self, local_time: float) -> np.ndarray:
        """
        Return the torque currently generated by the thruster.
        """

        actuator_torque = np.zeros(3)

        if self.command_mode == "PWM":

            if local_time < self.on_time:

                actuator_torque[self.controlled_axis] = (
                    self.thrust_direction * self.maximum_torque
                )

        elif self.command_mode == "bangbang":

            if self.is_firing:

                actuator_torque[self.controlled_axis] = (
                    self.thrust_direction * self.maximum_torque
                )

        return actuator_torque

    # ==========================================================
    # Internal command models
    # ==========================================================

    def _compute_pwm_command(self, projected_torque: float):
        """
        Compute PWM valve opening time.
        """

        duty_cycle = projected_torque / self.maximum_torque
        duty_cycle = np.clip(duty_cycle, 0.0, 1.0)

        self.on_time = (
            duty_cycle * self.modulation_window
        )

        if self.on_time < self.minimum_on_time:

            self.on_time = 0.0

    def _compute_bangbang_command(self, projected_torque: float):
        """
        Compute bang-bang firing state.
        """

        self.is_firing = (
            projected_torque >= self.activation_threshold
        )

    def get_output(self) -> 'ActuatorOutput':
        """
        Return the current output of the actuator.
        """
        pass 