import os

import numpy as np
import matplotlib.pyplot as plt


# ==============================================================================
# CONFIGURATION
# ==============================================================================

CHASER_NAME = "Chaser"
TARGET_NAME = "Target"

SIM_UNIQUE_ID = "1790778680601"

BASE_DIRECTORY = "sim_data/simulation_"

HISTORY_DIRECTORY = BASE_DIRECTORY + SIM_UNIQUE_ID

TIME_FACTOR_SEC = (
    27.321661 / (2.0 * np.pi) * 24 * 3600
)

SIM_MAX_TIME = 0.75952417 * 2 * TIME_FACTOR_SEC
ORBIT_MAX_TIME = SIM_MAX_TIME
RELATIVE_MAX_TIME = 60 * 12


# ==============================================================================
# LOAD SPACECRAFT CSV
# ==============================================================================

def load_spacecraft_history(
    spacecraft_name,
    directory,
):
    """
    Load the complete CSV history of a spacecraft.

    The CSV is generated by save_simulation_history_csv() and
    contains all recorded history variables in columns.
    """

    path = os.path.join(
        directory,
        f"{spacecraft_name}.csv",
    )

    if not os.path.isfile(path):
        raise FileNotFoundError(
            f"Spacecraft history not found:\n{path}"
        )

    data = np.genfromtxt(
        path,
        delimiter=",",
        names=True,
    )

    return data


# ==============================================================================
# LOAD CHASER AND TARGET
# ==============================================================================

chaser_data = load_spacecraft_history(
    CHASER_NAME,
    HISTORY_DIRECTORY,
)

target_data = load_spacecraft_history(
    TARGET_NAME,
    HISTORY_DIRECTORY,
)


# ==============================================================================
# EXTRACT TIME AND TRUE POSITION
# ==============================================================================

chaser_t = np.asarray(
    chaser_data["t"]
)

chaser_position = np.column_stack(
    [
        chaser_data["true_position_0"],
        chaser_data["true_position_1"],
        chaser_data["true_position_2"],
    ]
)


target_t = np.asarray(
    target_data["t"]
)

target_position = np.column_stack(
    [
        target_data["true_position_0"],
        target_data["true_position_1"],
        target_data["true_position_2"],
    ]
)


# ==============================================================================
# VALIDATE DATA
# ==============================================================================

if len(chaser_t) != len(chaser_position):
    raise ValueError(
        f"{CHASER_NAME}: time and position have different lengths: "
        f"{len(chaser_t)} vs {len(chaser_position)}"
    )

if len(target_t) != len(target_position):
    raise ValueError(
        f"{TARGET_NAME}: time and position have different lengths: "
        f"{len(target_t)} vs {len(target_position)}"
    )


# ==============================================================================
# SORT BY TIME
# ==============================================================================

chaser_indices = np.argsort(chaser_t)

chaser_t = chaser_t[chaser_indices]
chaser_position = chaser_position[chaser_indices]


target_indices = np.argsort(target_t)

target_t = target_t[target_indices]
target_position = target_position[target_indices]


# ==============================================================================
# COMMON TIME FOR COMPLETE ORBIT
# ==============================================================================

orbit_t_min = max(
    chaser_t[0],
    target_t[0],
)

orbit_t_max = min(
    chaser_t[-1],
    target_t[-1],
    ORBIT_MAX_TIME,
)

if orbit_t_max <= orbit_t_min:
    raise ValueError(
        "No common time interval exists for the complete orbit."
    )


chaser_orbit_mask = (
    (chaser_t >= orbit_t_min)
    &
    (chaser_t <= orbit_t_max)
)

target_orbit_mask = (
    (target_t >= orbit_t_min)
    &
    (target_t <= orbit_t_max)
)

chaser_orbit_t = chaser_t[
    chaser_orbit_mask
]

target_orbit_t = target_t[
    target_orbit_mask
]


orbit_t = np.unique(
    np.concatenate(
        [
            chaser_orbit_t,
            target_orbit_t,
        ]
    )
)


# ==============================================================================
# INTERPOLATE COMPLETE ORBIT
# ==============================================================================

chaser_orbit_position = np.column_stack(
    [
        np.interp(
            orbit_t,
            chaser_t,
            chaser_position[:, i],
        )
        for i in range(3)
    ]
)


target_orbit_position = np.column_stack(
    [
        np.interp(
            orbit_t,
            target_t,
            target_position[:, i],
        )
        for i in range(3)
    ]
)


# ==============================================================================
# COMMON TIME FOR RELATIVE MOTION
# ==============================================================================

relative_t_min = max(
    chaser_t[0],
    target_t[0],
)

relative_t_max = min(
    chaser_t[-1],
    target_t[-1],
    RELATIVE_MAX_TIME,
)

if relative_t_max <= relative_t_min:
    raise ValueError(
        "No common time interval exists for the relative motion."
    )


chaser_relative_mask = (
    (chaser_t >= relative_t_min)
    &
    (chaser_t <= relative_t_max)
)

target_relative_mask = (
    (target_t >= relative_t_min)
    &
    (target_t <= relative_t_max)
)

chaser_relative_t = chaser_t[
    chaser_relative_mask
]

target_relative_t = target_t[
    target_relative_mask
]


relative_t = np.unique(
    np.concatenate(
        [
            chaser_relative_t,
            target_relative_t,
        ]
    )
)


# ==============================================================================
# INTERPOLATE RELATIVE MOTION
# ==============================================================================

chaser_relative_position = np.column_stack(
    [
        np.interp(
            relative_t,
            chaser_t,
            chaser_position[:, i],
        )
        for i in range(3)
    ]
)


target_relative_position = np.column_stack(
    [
        np.interp(
            relative_t,
            target_t,
            target_position[:, i],
        )
        for i in range(3)
    ]
)


# ==============================================================================
# RELATIVE POSITION
#
# r_C/T = r_C - r_T
# ==============================================================================

relative_position = (
    chaser_relative_position
    - target_relative_position
)


# ==============================================================================
# FIGURE — TRAJECTORIES
# ==============================================================================

fig = plt.figure(
    figsize=(18, 6),
)


# ==============================================================================
# SUBPLOT 1 — ABSOLUTE ORBIT
# ==============================================================================

ax1 = fig.add_subplot(
    1,
    3,
    1,
    projection="3d",
)


ax1.plot(
    chaser_orbit_position[:, 0],
    chaser_orbit_position[:, 1],
    chaser_orbit_position[:, 2],
    label=CHASER_NAME,
)


ax1.plot(
    target_orbit_position[:, 0],
    target_orbit_position[:, 1],
    target_orbit_position[:, 2],
    label=TARGET_NAME,
)


# Moon position in CR3BP

MU = 1.215e-2
LENGTH_FACTOR = 384400.0e3

ax1.scatter(
    (1 - MU) * LENGTH_FACTOR,
    0,
    0,
    marker="o",
    color="white",
    edgecolors="black",
    label="Moon",
)


ax1.set_title(
    "Complete Orbit (During 1 rev) - NRHO L2",
    fontweight="bold",
)

ax1.set_xlabel("X [m]")
ax1.set_ylabel("Y [m]")
ax1.set_zlabel("Z [m]")

ax1.legend()


# ==============================================================================
# SUBPLOT 2 — RELATIVE POSITION VS TIME
# ==============================================================================

ax2 = fig.add_subplot(
    1,
    3,
    2,
)


labels = (
    r"$\Delta x$",
    r"$\Delta y$",
    r"$\Delta z$",
)


for i in range(3):

    ax2.plot(
        relative_t,
        relative_position[:, i],
        linewidth=1.3,
        label=labels[i],
    )


ax2.axhline(
    0.0,
    linestyle="--",
    linewidth=0.8,
)


ax2.set_title(
    "Relative Position",
    fontweight="bold",
)

ax2.set_xlabel(
    "Time [s]"
)

ax2.set_ylabel(
    "Relative Position [m]"
)

ax2.set_xlim(
    relative_t_min,
    relative_t_max,
)

ax2.legend(
    fontsize=8,
)


# ==============================================================================
# SUBPLOT 3 — RELATIVE TRAJECTORY
# ==============================================================================

ax3 = fig.add_subplot(
    1,
    3,
    3,
    projection="3d",
)


ax3.plot(
    relative_position[:, 0],
    relative_position[:, 1],
    relative_position[:, 2],
    linewidth=1.3,
    label=CHASER_NAME,
)


# Target fixed at origin

ax3.scatter(
    0.0,
    0.0,
    0.0,
    marker="o",
    s=50,
    label=TARGET_NAME,
)


# Initial relative position

ax3.scatter(
    relative_position[0, 0],
    relative_position[0, 1],
    relative_position[0, 2],
    marker="o",
    s=35,
    label="Chaser Relative Initial Position",
)


# Final relative position

ax3.scatter(
    relative_position[-1, 0],
    relative_position[-1, 1],
    relative_position[-1, 2],
    marker="x",
    s=50,
    label="Chaser Relative Final Position",
)


ax3.set_title(
    "Relative Trajectory",
    fontweight="bold",
)

ax3.set_xlabel(
    r"$\Delta x$ [m]"
)

ax3.set_ylabel(
    r"$\Delta y$ [m]"
)

ax3.set_zlabel(
    r"$\Delta z$ [m]"
)

ax3.legend(
    fontsize=8,
)


# Rotate camera

ax3.view_init(
    elev=25,
    azim=135,
)


# ==============================================================================
# EQUAL ASPECT RATIO FOR 3D PLOTS
# ==============================================================================

def set_equal_3d_axes(
    ax,
    data,
):

    x = data[:, 0]
    y = data[:, 1]
    z = data[:, 2]

    x_range = np.ptp(x)
    y_range = np.ptp(y)
    z_range = np.ptp(z)

    max_range = max(
        x_range,
        y_range,
        z_range,
    )

    if max_range == 0:
        max_range = 1.0

    x_mid = (
        x.max()
        + x.min()
    ) / 2

    y_mid = (
        y.max()
        + y.min()
    ) / 2

    z_mid = (
        z.max()
        + z.min()
    ) / 2

    ax.set_xlim(
        x_mid - max_range / 2,
        x_mid + max_range / 2,
    )

    ax.set_ylim(
        y_mid - max_range / 2,
        y_mid + max_range / 2,
    )

    ax.set_zlim(
        z_mid - max_range / 2,
        z_mid + max_range / 2,
    )


set_equal_3d_axes(
    ax1,
    np.vstack(
        [
            chaser_orbit_position,
            target_orbit_position,
        ]
    ),
)


set_equal_3d_axes(
    ax3,
    np.vstack(
        [
            relative_position,
            np.zeros((1, 3)),
        ]
    ),
)


# ==============================================================================
# FIGURE TITLE
# ==============================================================================

fig.suptitle(
    "SIMULATION RESULTS - TRAJECTORIES",
    fontsize=14,
    fontweight="bold",
)


fig.tight_layout(
    rect=[0, 0, 1, 0.94],
)


plt.show()


# ==============================================================================
# CHASER CONTROL RESULT
# ==============================================================================

# The control variables are already present in the Chaser CSV.
# No additional files need to be loaded.

control_force = np.column_stack(
    [
        chaser_data["control_force_0"],
        chaser_data["control_force_1"],
        chaser_data["control_force_2"],
    ]
)


applied_force = np.column_stack(
    [
        chaser_data["current_force_exerted_0"],
        chaser_data["current_force_exerted_1"],
        chaser_data["current_force_exerted_2"],
    ]
)


control_torque = np.column_stack(
    [
        chaser_data["control_torque_0"],
        chaser_data["control_torque_1"],
        chaser_data["control_torque_2"],
    ]
)


applied_torque = np.column_stack(
    [
        chaser_data["current_torque_exerted_0"],
        chaser_data["current_torque_exerted_1"],
        chaser_data["current_torque_exerted_2"],
    ]
)


# ==============================================================================
# SORT CONTROL DATA USING THE SAME TIME ORDER
# ==============================================================================

control_indices = np.argsort(
    chaser_data["t"]
)

chaser_control_t = np.asarray(
    chaser_data["t"]
)[control_indices]

control_force = control_force[
    control_indices
]

applied_force = applied_force[
    control_indices
]

control_torque = control_torque[
    control_indices
]

applied_torque = applied_torque[
    control_indices
]


# ==============================================================================
# LIMIT TO RELATIVE_MAX_TIME
# ==============================================================================

control_mask = (
    chaser_control_t <= RELATIVE_MAX_TIME
)


control_t = chaser_control_t[
    control_mask
]

control_force = control_force[
    control_mask
]

applied_force = applied_force[
    control_mask
]

control_torque = control_torque[
    control_mask
]

applied_torque = applied_torque[
    control_mask
]


if len(control_t) == 0:
    raise ValueError(
        "No Chaser control data exists within RELATIVE_MAX_TIME."
    )


# ==============================================================================
# FIGURE — CONTROL EFFORT
# ==============================================================================

fig, axes = plt.subplots(
    3,
    2,
    figsize=(13, 9),
    sharex=True,
)


labels = (
    "X",
    "Y",
    "Z",
)


for i, label in enumerate(labels):

    # --------------------------------------------------------------------------
    # FORCE
    # --------------------------------------------------------------------------

    ax = axes[i, 0]

    ax.plot(
        control_t,
        control_force[:, i],
        linestyle="--",
        label="Commanded",
        zorder=2,
    )

    ax.plot(
        control_t,
        applied_force[:, i],
        linestyle="-",
        label="Applied",
        zorder=1,
    )

    ax.set_title(
        f"Force {label}",
        fontweight="bold",
    )

    ax.set_ylabel(
        rf"$F_{{{label.lower()}}}$ [N]"
    )

    ax.legend()


    # --------------------------------------------------------------------------
    # TORQUE
    # --------------------------------------------------------------------------

    ax = axes[i, 1]

    ax.plot(
        control_t,
        control_torque[:, i],
        linestyle="--",
        label="Commanded",
        zorder=2,
    )

    ax.plot(
        control_t,
        applied_torque[:, i],
        linestyle="-",
        label="Applied",
        zorder=1,
    )

    ax.set_title(
        f"Torque {label}",
        fontweight="bold",
    )

    ax.set_ylabel(
        rf"$\tau_{{{label.lower()}}}$ [N·m]"
    )

    ax.legend()


# ==============================================================================
# X AXIS
# ==============================================================================

axes[-1, 0].set_xlabel(
    "Time [s]"
)

axes[-1, 1].set_xlabel(
    "Time [s]"
)


# ==============================================================================
# FIGURE TITLE
# ==============================================================================

fig.suptitle(
    "SIMULATION RESULT - CONTROL EFFORT CHASER",
    fontsize=14,
    fontweight="bold",
)

fig.tight_layout()


plt.show()